language: node_js

node_js:
  - 'node'
  - '10'
  - '6'

sudo: false

env:
  - workerCount=3 timeout=600000

matrix:
  fast_finish: true

branches:
  only:
  - master
  - release-2.7
  - release-2.8
  - release-2.9
  - release-3.0
  - release-3.1

script:
  - npm run test

cache:
  directories:
    - node_modules

git:
depth: 1
